// offline_dict.js - Diccionario local ultrarrápido para traducción inmediata (0ms) sin internet
const OFFLINE_DICTIONARY = {
  "us": { "t": "nosotros, a nosotros, nos", "p": "[ʌs]" },
  "we": { "t": "nosotros, nosotras", "p": "[wiː]" },
  "our": { "t": "nuestro, nuestra", "p": "[ˈaʊə]" },
  "ours": { "t": "el nuestro, lo nuestro", "p": "[ˈaʊəz]" },
  "you": { "t": "tú, usted, ustedes", "p": "[juː]" },
  "your": { "t": "tu, su", "p": "[jɔː]" },
  "yours": { "t": "tuyo, suyo", "p": "[jɔːz]" },
  "they": { "t": "ellos, ellas", "p": "[ðeɪ]" },
  "them": { "t": "a ellos, les, los, las", "p": "[ðem]" },
  "their": { "t": "su, sus (de ellos)", "p": "[ðeə]" },
  "theirs": { "t": "el de ellos, suyo", "p": "[ðeəz]" },
  "he": { "t": "él", "p": "[hiː]" },
  "him": { "t": "a él, le, lo", "p": "[hɪm]" },
  "his": { "t": "su, de él, suyo", "p": "[hɪz]" },
  "she": { "t": "ella", "p": "[ʃiː]" },
  "her": { "t": "su, a ella, la, le", "p": "[hɜː]" },
  "hers": { "t": "el de ella, suyo", "p": "[hɜːz]" },
  "it": { "t": "eso, ello, lo", "p": "[ɪt]" },
  "its": { "t": "su (de ello)", "p": "[ɪts]" },
  "me": { "t": "mí, me", "p": "[miː]" },
  "my": { "t": "mi, mis", "p": "[maɪ]" },
  "mine": { "t": "mío, mía", "p": "[maɪn]" },
  "this": { "t": "este, esta, esto", "p": "[ðɪs]" },
  "that": { "t": "ese, esa, aquel, que", "p": "[ðæt]" },
  "these": { "t": "estos, estas", "p": "[ðiːz]" },
  "those": { "t": "esos, esas, aquellos", "p": "[ðəʊz]" },
  "with": { "t": "con", "p": "[wɪð]" },
  "for": { "t": "para, por", "p": "[fɔː]" },
  "from": { "t": "de, desde", "p": "[frɒm]" },
  "to": { "t": "a, hacia, para", "p": "[tuː]" },
  "in": { "t": "en, dentro de", "p": "[ɪn]" },
  "on": { "t": "en, sobre", "p": "[ɒn]" },
  "at": { "t": "en, a", "p": "[æt]" },
  "by": { "t": "por, junto a", "p": "[baɪ]" },
  "of": { "t": "de", "p": "[ɒv]" },
  "and": { "t": "y, e", "p": "[ænd]" },
  "or": { "t": "o, u", "p": "[ɔː]" },
  "but": { "t": "pero, sino", "p": "[bʌt]" },
  "so": { "t": "así que, tan", "p": "[səʊ]" },
  "as": { "t": "como, mientras", "p": "[æz]" },
  "if": { "t": "si (condicional)", "p": "[ɪf]" },
  "can": { "t": "poder, puede, lata", "p": "[kæn]" },
  "could": { "t": "podría, pudo", "p": "[kʊd]" },
  "will": { "t": "hará (futuro), voluntad", "p": "[wɪl]" },
  "would": { "t": "haría (condicional)", "p": "[wʊd]" },
  "should": { "t": "debería", "p": "[ʃʊd]" },
  "must": { "t": "debe, tener que", "p": "[mʌst]" },
  "have": { "t": "tener, haber", "p": "[hæv]" },
  "has": { "t": "tiene, ha", "p": "[hæz]" },
  "had": { "t": "tenía, había", "p": "[hæd]" },
  "do": { "t": "hacer", "p": "[duː]" },
  "does": { "t": "hace", "p": "[dʌz]" },
  "did": { "t": "hizo", "p": "[dɪd]" },
  "be": { "t": "ser, estar", "p": "[biː]" },
  "is": { "t": "es, está", "p": "[ɪz]" },
  "are": { "t": "son, están", "p": "[ɑː]" },
  "was": { "t": "era, fue, estaba", "p": "[wɒz]" },
  "were": { "t": "eran, fueron, estaban", "p": "[wɜː]" },
  "been": { "t": "sido, estado", "p": "[biːn]" },
  "not": { "t": "no", "p": "[nɒt]" },
  "all": { "t": "todo, todos", "p": "[ɔːl]" },
  "some": { "t": "alguno, algunos", "p": "[sʌm]" },
  "any": { "t": "cualquier, alguno", "p": "[ˈeni]" },
  "just": { "t": "solo, justo, recién", "p": "[dʒʌst]" },
  "very": { "t": "muy", "p": "[ˈveri]" },
  "screen": { "t": "pantalla", "p": "[skriːn]" },
  "screens": { "t": "pantallas", "p": "[skriːnz]" },
  "week": { "t": "semana", "p": "[wiːk]" },
  "weeks": { "t": "semanas", "p": "[wiːks]" },
  "software": { "t": "software, programas", "p": "[ˈsɒftweə]" },
  "office": { "t": "oficina", "p": "[ˈɒfɪs]"},
  "offices": { "t": "oficinas", "p": "[ˈɒfɪsɪz]"},
  "developer": { "t": "desarrollador", "p": "[dɪˈveləpə]" },
  "developers": { "t": "desarrolladores", "p": "[dɪˈveləpəz]" },
  "development": { "t": "desarrollo", "p": "[dɪˈveləpmənt]" },
  "code": { "t": "código", "p": "[kəʊd]" },
  "coding": { "t": "programación, codificación", "p": "[ˈkəʊdɪŋ]" },
  "launch": { "t": "lanzar, lanzamiento", "p": "[lɔːntʃ]" },
  "launching": { "t": "lanzando, estreno", "p": "[ˈlɔːntʃɪŋ]" },
  "launched": { "t": "lanzado", "p": "[lɔːntʃt]" },
  "startup": { "t": "empresa emergente", "p": "[ˈstɑːtʌp]" },
  "young": { "t": "joven", "p": "[jʌŋ]" },
  "people": { "t": "personas, gente", "p": "[ˈpiːpl]" },
  "person": { "t": "persona", "p": "[ˈpɜːsn]" },
  "work": { "t": "trabajo, trabajar", "p": "[wɜːk]" },
  "working": { "t": "trabajando", "p": "[ˈwɜːkɪŋ]" },
  "worker": { "t": "trabajador", "p": "[ˈwɜːkə]" },
  "speech": { "t": "discurso, habla", "p": "[spiːtʃ]" },
  "finish": { "t": "terminar", "p": "[ˈfɪnɪʃ]" },
  "finishing": { "t": "terminando", "p": "[ˈfɪnɪʃɪŋ]" },
  "finished": { "t": "terminado", "p": "[ˈfɪnɪʃt]" },
  "room": { "t": "habitación, sala", "p": "[ruːm]" },
  "smile": { "t": "sonreír, sonrisa", "p": "[smaɪl]" },
  "smiled": { "t": "sonrió", "p": "[smaɪld]" },
  "nod": { "t": "asentir con la cabeza", "p": "[nɒd]" },
  "nodded": { "t": "asintió", "p": "[ˈnɒdɪd]" },
  "excitement": { "t": "emoción, entusiasmo", "p": "[ɪkˈsaɪtmənt]"},
  "release": { "t": "lanzamiento, publicar", "p": "[rɪˈliːs]" },
  "released": { "t": "lanzado, publicado", "p": "[rɪˈliːst]" },
  "upcoming": { "t": "próximo, venidero", "p": "[ˈʌpkʌmɪŋ]" },
  "time": { "t": "tiempo, vez, hora", "p": "[taɪm]" },
  "year": { "t": "año", "p": "[jɪə]" },
  "years": { "t": "años", "p": "[jɪəz]" },
  "way": { "t": "camino, manera, forma", "p": "[weɪ]" },
  "day": { "t": "día", "p": "[deɪ]" },
  "days": { "t": "días", "p": "[deɪz]" },
  "man": { "t": "hombre", "p": "[mæn]" },
  "men": { "t": "hombres", "p": "[men]" },
  "woman": { "t": "mujer", "p": "[ˈwʊmən]" },
  "women": { "t": "mujeres", "p": "[ˈwɪmɪn]" },
  "child": { "t": "niño, niña", "p": "[tʃaɪld]" },
  "children": { "t": "niños, hijos", "p": "[ˈtʃɪldrən]" },
  "company": { "t": "empresa, compañía", "p": "[ˈkʌmpəni]" },
  "companies": { "t": "empresas", "p": "[ˈkʌmpəniz]" },
  "number": { "t": "número", "p": "[ˈnʌmbə]" },
  "group": { "t": "grupo", "p": "[ɡruːp]" },
  "problem": { "t": "problema", "p": "[ˈprɒbləm]" },
  "problems": { "t": "problemas", "p": "[ˈprɒbləmz]" },
  "fact": { "t": "hecho, dato", "p": "[fækt]" },
  "world": { "t": "mundo", "p": "[wɜːld]" },
  "hand": { "t": "mano", "p": "[hænd]" },
  "hands": { "t": "manos", "p": "[hændz]" },
  "part": { "t": "parte", "p": "[pɑːt]" },
  "parts": { "t": "partes", "p": "[pɑːts]" },
  "place": { "t": "lugar", "p": "[pleɪs]" },
  "case": { "t": "caso", "p": "[keɪs]" },
  "point": { "t": "punto, señalar", "p": "[pɔɪnt]" },
  "life": { "t": "vida", "p": "[laɪf]" },
  "eye": { "t": "ojo", "p": "[aɪ]" },
  "eyes": { "t": "ojos", "p": "[aɪz]" },
  "system": { "t": "sistema", "p": "[ˈsɪstəm]" },
  "program": { "t": "programa", "p": "[ˈprəʊɡræm]" },
  "question": { "t": "pregunta", "p": "[ˈkwestʃən]" },
  "questions": { "t": "preguntas", "p": "[ˈkwestʃənz]" },
  "business": { "t": "negocio, empresa", "p": "[ˈbɪznəs]" },
  "issue": { "t": "asunto, problema, tema", "p": "[ˈɪʃuː]" },
  "side": { "t": "lado", "p": "[saɪd]" },
  "kind": { "t": "tipo, clase, amable", "p": "[kaɪnd]" },
  "head": { "t": "cabeza, líder", "p": "[hed]" },
  "house": { "t": "casa", "p": "[haʊs]" },
  "service": { "t": "servicio", "p": "[ˈsɜːvɪs]" },
  "services": { "t": "servicios", "p": "[ˈsɜːvɪsɪz]" },
  "friend": { "t": "amigo/a", "p": "[frend]" },
  "friends": { "t": "amigos", "p": "[frendz]" },
  "father": { "t": "padre", "p": "[ˈfɑːðə]" },
  "mother": { "t": "madre", "p": "[ˈmʌðə]" },
  "area": { "t": "área, zona", "p": "[ˈeəriə]" },
  "water": { "t": "agua", "p": "[ˈwɔːtə]" },
  "money": { "t": "dinero", "p": "[ˈmʌni]" },
  "story": { "t": "historia, relato", "p": "[ˈstɔːri]" },
  "month": { "t": "mes", "p": "[mʌnθ]" },
  "months": { "t": "meses", "p": "[mʌnθs]" },
  "book": { "t": "libro", "p": "[bʊk]" },
  "books": { "t": "libros", "p": "[bʊks]" },
  "word": { "t": "palabra", "p": "[wɜːd]" },
  "words": { "t": "palabras", "p": "[wɜːdz]" },
  "name": { "t": "nombre", "p": "[neɪm]" },
  "names": { "t": "nombres", "p": "[neɪmz]" },
  "study": { "t": "estudiar, estudio", "p": "[ˈstʌdi]" },
  "learn": { "t": "aprender", "p": "[lɜːn]" },
  "learning": { "t": "aprendizaje, aprendiendo", "p": "[ˈlɜːnɪŋ]" },
  "learned": { "t": "aprendido", "p": "[lɜːnd]" },
  "read": { "t": "leer, leído", "p": "[riːd]" },
  "reading": { "t": "leyendo, lectura", "p": "[ˈriːdɪŋ]" },
  "write": { "t": "escribir", "p": "[raɪt]" },
  "writing": { "t": "escribiendo, escritura", "p": "[ˈraɪtɪŋ]" },
  "written": { "t": "escrito", "p": "[ˈrɪtn]" },
  "listen": { "t": "escuchar", "p": "[ˈlɪsn]" },
  "speak": { "t": "hablar", "p": "[spiːk]"},
  "understand": { "t": "entender, comprender", "p": "[ˌʌndəˈstænd]" },
  "understanding": { "t": "comprensión", "p": "[ˌʌndəˈstændɪŋ]" },
  "remember": { "t": "recordar", "p": "[rɪˈmembə]" },
  "know": { "t": "saber, conocer", "p": "[nəʊ]" },
  "known": { "t": "conocido, sabido", "p": "[nəʊn]" },
  "think": { "t": "pensar", "p": "[θɪŋk]" },
  "thought": { "t": "pensamiento, pensó", "p": "[θɔːt]" },
  "thinking": { "t": "pensamiento, pensando", "p": "[ˈθɪŋkɪŋ]" },
  "see": { "t": "ver", "p": "[siː]" },
  "saw": { "t": "vio", "p": "[sɔː]" },
  "seen": { "t": "visto", "p": "[siːn]" },
  "look": { "t": "mirar, parecer", "p": "[lʊk]" },
  "looking": { "t": "mirando, buscando", "p": "[ˈlʊkɪŋ]" },
  "want": { "t": "querer, desear", "p": "[wɒnt]" },
  "wanted": { "t": "quería, querido", "p": "[ˈwɒntɪd]" },
  "give": { "t": "dar", "p": "[ɡɪv]" },
  "given": { "t": "dado", "p": "[ˈɡɪvn]" },
  "use": { "t": "usar, utilizar", "p": "[juːz]" },
  "used": { "t": "usado, solía", "p": "[juːzd]" },
  "user": { "t": "usuario", "p": "[ˈjuːzə]" },
  "users": { "t": "usuarios", "p": "[ˈjuːzəz]" },
  "find": { "t": "encontrar", "p": "[faɪnd]" },
  "found": { "t": "encontró, encontrado", "p": "[faʊnd]" },
  "tell": { "t": "decir, contar", "p": "[tel]" },
  "told": { "t": "dijo, contado", "p": "[təʊld]" },
  "ask": { "t": "preguntar, pedir", "p": "[ɑːsk]" },
  "asked": { "t": "preguntó", "p": "[ɑːskt]" },
  "need": { "t": "necesitar, necesidad", "p": "[niːd]" },
  "needed": { "t": "necesario, necesitó", "p": "[ˈniːdɪd]" },
  "feel": { "t": "sentir", "p": "[fiːl]" },
  "feeling": { "t": "sentimiento, sintiendo", "p": "[ˈfiːlɪŋ]" },
  "become": { "t": "llegar a ser, convertirse", "p": "[bɪˈkʌm]" },
  "leave": { "t": "dejar, salir", "p": "[liːv]" },
  "put": { "t": "poner, colocar", "p": "[pʊt]" },
  "mean": { "t": "significar, querer decir", "p": "[miːn]" },
  "meaning": { "t": "significado", "p": "[ˈmiːnɪŋ]" },
  "keep": { "t": "mantener, guardar", "p": "[kiːp]" },
  "kept": { "t": "mantuvo, guardó", "p": "[kept]" },
  "let": { "t": "permitir, dejar", "p": "[let]" },
  "begin": { "t": "empezar, comenzar", "p": "[bɪˈɡɪn]" },
  "seem": { "t": "parecer", "p": "[siːm]"},
  "seemed": { "t": "parecía", "p": "[siːmd]" },
  "help": { "t": "ayudar, ayuda", "p": "[help]" },
  "talk": { "t": "conversar, hablar", "p": "[tɔːk]" },
  "turn": { "t": "girar, turno", "p": "[tɜːn]" },
  "start": { "t": "comenzar, iniciar", "p": "[stɑːt]" },
  "started": { "t": "comenzó", "p": "[ˈstɑːtɪd]" },
  "show": { "t": "mostrar, espectáculo", "p": "[ʃəʊ]" },
  "shown": { "t": "mostrado", "p": "[ʃəʊn]" },
  "hear": { "t": "oír, escuchar", "p": "[hɪə]" },
  "heard": { "t": "oyó, escuchado", "p": "[hɜːd]" },
  "play": { "t": "jugar, reproducir", "p": "[pleɪ]" },
  "run": { "t": "correr, ejecutar", "p": "[rʌn]"},
  "running": { "t": "corriendo, ejecutando", "p": "[ˈrʌnɪŋ]"},
  "move": { "t": "mover, mudarse", "p": "[muːv]" },
  "movement": { "t": "movimiento", "p": "[ˈmuːvmənt]" },
  "live": { "t": "vivir, en vivo", "p": "[lɪv]" },
  "believe": { "t": "creer", "p": "[bɪˈliːv]" },
  "bring": { "t": "traer, llevar", "p": "[brɪŋ]" },
  "brought": { "t": "trajo", "p": "[brɔːt]" },
  "happen": { "t": "ocurrir, pasar", "p": "[ˈhæpən]" },
  "happened": { "t": "ocurrió, pasó", "p": "[ˈhæpənd]" },
  "provide": { "t": "proporcionar, proveer", "p": "[prəˈvaɪd]" },
  "provided": { "t": "proporcionado", "p": "[prəˈvaɪdɪd]" },
  "sit": { "t": "sentarse", "p": "[sɪt]" },
  "stand": { "t": "estar de pie, soportar", "p": "[stænd]" },
  "lose": { "t": "perder", "p": "[luːz]" },
  "lost": { "t": "perdido", "p": "[lɒst]" },
  "pay": { "t": "pagar", "p": "[peɪ]" },
  "meet": { "t": "conocer, reunirse", "p": "[miːt]" },
  "include": { "t": "incluir", "p": "[ɪnˈkluːd]" },
  "included": { "t": "incluido", "p": "[ɪnˈkluːdɪd]" },
  "continue": { "t": "continuar, seguir", "p": "[kənˈtɪnjuː]" },
  "set": { "t": "establecer, conjunto", "p": "[set]" },
  "change": { "t": "cambiar, cambio", "p": "[tʃeɪndʒ]" },
  "changed": { "t": "cambiado", "p": "[tʃeɪndʒd]" },
  "lead": { "t": "liderar, guiar", "p": "[liːd]" },
  "stop": { "t": "parar, detenerse", "p": "[stɒp]" },
  "create": { "t": "crear", "p": "[kriˈeɪt]" },
  "created": { "t": "creado", "p": "[kriˈeɪtɪd]" },
  "allow": { "t": "permitir", "p": "[əˈlaʊ]" },
  "add": { "t": "añadir, agregar", "p": "[æd]" },
  "added": { "t": "añadido", "p": "[ˈædɪd]" },
  "spend": { "t": "gastar, pasar (tiempo)", "p": "[spend]" },
  "grow": { "t": "crecer, cultivar", "p": "[ɡrəʊ]" },
  "open": { "t": "abrir, abierto", "p": "[ˈəʊpən]" },
  "walk": { "t": "caminar, paseo", "p": "[wɔːk]" },
  "win": { "t": "ganar", "p": "[wɪn]" },
  "offer": { "t": "ofrecer, oferta", "p": "[ˈɒfə]" },
  "love": { "t": "amar, encantar, amor", "p": "[lʌv]" },
  "consider": { "t": "considerar", "p": "[kənˈsɪdə]" },
  "appear": { "t": "aparecer", "p": "[əˈpɪə]" },
  "buy": { "t": "comprar", "p": "[baɪ]" },
  "wait": { "t": "esperar", "p": "[weɪt]" },
  "serve": { "t": "servir", "p": "[sɜːv]" },
  "send": { "t": "enviar", "p": "[send]" },
  "sent": { "t": "enviado", "p": "[sent]" },
  "build": { "t": "construir", "p": "[bɪld]" },
  "built": { "t": "construido", "p": "[bɪlt]" },
  "stay": { "t": "quedarse, permanecer", "p": "[steɪ]" },
  "fall": { "t": "caer, otoño", "p": "[fɔːl]" },
  "cut": { "t": "cortar", "p": "[kʌt]" },
  "reach": { "t": "alcanzar, llegar a", "p": "[riːtʃ]" },
  "remain": { "t": "permanecer", "p": "[rɪˈmeɪn]" },
  "good": { "t": "bueno, bien", "p": "[ɡʊd]" },
  "new": { "t": "nuevo", "p": "[njuː]" },
  "first": { "t": "primero", "p": "[fɜːst]" },
  "last": { "t": "último, durar", "p": "[lɑːst]" },
  "long": { "t": "largo", "p": "[lɒŋ]" },
  "great": { "t": "gran, genial, excelente", "p": "[ɡreɪt]" },
  "little": { "t": "pequeño, poco", "p": "[ˈlɪtl]" },
  "own": { "t": "propio, poseer", "p": "[əʊn]" },
  "other": { "t": "otro", "p": "[ˈʌðə]" },
  "old": { "t": "viejo, antiguo", "p": "[əʊld]" },
  "right": { "t": "correcto, derecho/a", "p": "[raɪt]" },
  "big": { "t": "grande", "p": "[bɪɡ]" },
  "high": { "t": "alto", "p": "[haɪ]" },
  "different": { "t": "diferente, distinto", "p": "[ˈdɪfrənt]" },
  "small": { "t": "pequeño", "p": "[smɔːl]" },
  "smaller": { "t": "más pequeño", "p": "[ˈsmɔːlə]" },
  "large": { "t": "grande, amplio", "p": "[lɑːdʒ]" },
  "next": { "t": "siguiente, próximo", "p": "[nekst]" },
  "early": { "t": "temprano", "p": "[ˈɜːli]" },
  "important": { "t": "importante", "p": "[ɪmˈpɔːtnt]" },
  "few": { "t": "pocos, unos pocos", "p": "[fjuː]" },
  "public": { "t": "público", "p": "[ˈpʌblɪk]" },
  "bad": { "t": "malo", "p": "[bæd]" },
  "same": { "t": "mismo, igual", "p": "[seɪm]" },
  "able": { "t": "capaz", "p": "[ˈeɪbl]" },
  "easy": { "t": "fácil", "p": "[ˈiːzi]"},
  "hard": { "t": "difícil, duro", "p": "[hɑːd]" },
  "clear": { "t": "claro", "p": "[klɪə]" },
  "simple": { "t": "simple, sencillo", "p": "[ˈsɪmpl]" },
  "fast": { "t": "rápido", "p": "[fɑːst]" },
  "slow": { "t": "lento", "p": "[sləʊ]" },
  "sure": { "t": "seguro, seguro de", "p": "[ʃʊə]" },
  "free": { "t": "gratis, libre", "p": "[friː]" },
  "true": { "t": "verdadero, cierto", "p": "[truː]" },
  "whole": { "t": "entero, todo", "p": "[həʊl]" },
  "short": { "t": "corto, bajo", "p": "[ʃɔːt]" },
  "single": { "t": "único, soltero", "p": "[ˈsɪŋɡl]" },
  "common": { "t": "común, habitual", "p": "[ˈkɒmən]" },
  "natural": { "t": "natural", "p": "[ˈnætʃrəl]" },
  "strong": { "t": "fuerte", "p": "[strɒŋ]" },
  "happy": { "t": "feliz, contento", "p": "[ˈhæpi]" },
  "ready": { "t": "listo, preparado", "p": "[ˈredi]" },
  "dark": { "t": "oscuro", "p": "[dɑːk]" },
  "final": { "t": "final", "p": "[ˈfaɪnl]" },
  "main": { "t": "principal", "p": "[meɪn]" },
  "green": { "t": "verde", "p": "[ɡriːn]" },
  "better": { "t": "mejor", "p": "[ˈbetə]" },
  "best": { "t": "el mejor", "p": "[best]" },
  "always": { "t": "siempre", "p": "[ˈɔːlweɪz]" },
  "never": { "t": "nunca, jamás", "p": "[ˈnevə]" },
  "often": { "t": "a menudo", "p": "[ˈɒfn]" },
  "sometimes": { "t": "a veces", "p": "[ˈsʌmtaɪmz]" },
  "today": { "t": "hoy", "p": "[təˈdeɪ]" },
  "together": { "t": "juntos", "p": "[təˈɡeðə]" },
  "already": { "t": "ya", "p": "[ɔːlˈredi]" },
  "website": { "t": "sitio web", "p": "[ˈwebsaɪt]" },
  "internet": { "t": "internet", "p": "[ˈɪntənet]" },
  "computer": { "t": "computadora", "p": "[kəmˈpjuːtə]" },
  "browser": { "t": "navegador", "p": "[ˈbraʊzə]" },
  "button": { "t": "botón", "p": "[ˈbʌtn]" },
  "window": { "t": "ventana", "p": "[ˈwɪndəʊ]" },
  "image": { "t": "imagen", "p": "[ˈɪmɪdʒ]" },
  "video": { "t": "video", "p": "[ˈvɪdiəʊ]" },
  "audio": { "t": "audio, sonido", "p": "[ˈɔːdiəʊ]" },
  "sound": { "t": "sonido", "p": "[saʊnd]" },
  "file": { "t": "archivo", "p": "[faɪl]" },
  "click": { "t": "hacer clic", "p": "[klɪk]" },
  "save": { "t": "guardar", "p": "[seɪv]" },
  "saved": { "t": "guardado", "p": "[seɪvd]" },
  "delete": { "t": "eliminar, borrar", "p": "[dɪˈliːt]" },
  "search": { "t": "buscar", "p": "[sɜːtʃ]" },
  "message": { "t": "mensaje", "p": "[ˈmesɪdʒ]" },
  "text": { "t": "texto", "p": "[tekst]" },
  "language": { "t": "idioma", "p": "[ˈlæŋɡwɪdʒ]" },
  "english": { "t": "inglés", "p": "[ˈɪŋɡlɪʃ]" },
  "spanish": { "t": "español", "p": "[ˈspænɪʃ]" },
  "translate": { "t": "traducir", "p": "[trænzˈleɪt]" },
  "translation": { "t": "traducción", "p": "[trænzˈleɪʃn]" },
  "card": { "t": "tarjeta", "p": "[kɑːd]" },
  "function": { "t": "función", "p": "[ˈfʌŋkʃn]" },
  "functions": { "t": "funciones", "p": "[ˈfʌŋkʃnz]" },
  "about": { "t": "acerca de, sobre", "p": "[əˈbaʊt]" },
  "before": { "t": "antes de", "p": "[bɪˈfɔː]" },
  "after": { "t": "después de", "p": "[ˈɑːftə]" },
  "under": { "t": "debajo de", "p": "[ˈʌndə]" },
  "above": { "t": "encima de", "p": "[əˈbʌv]" },
  "through": { "t": "a través de", "p": "[θruː]" },
  "because": { "t": "porque", "p": "[bɪˈkɒz]" },
  "while": { "t": "mientras", "p": "[waɪl]" },
  "what": { "t": "qué", "p": "[wɒt]" },
  "which": { "t": "cuál, que", "p": "[wɪtʃ]" },
  "who": { "t": "quién", "p": "[huː]" },
  "where": { "t": "dónde", "p": "[weə]" },
  "when": { "t": "cuándo", "p": "[wen]" },
  "how": { "t": "cómo", "p": "[haʊ]" },
  "draw": { "t": "dibujar, trazar", "p": "[drɔː]" },
  "drew": { "t": "dibujó", "p": "[druː]" },
  "drawn": { "t": "dibujado, trazado", "p": "[drɔːn]" },
  "drawing": { "t": "dibujo, trazando", "p": "[ˈdrɔːɪŋ]" },
  "smaller": { "t": "más pequeño", "p": "[ˈsmɔːlə]" },
  "smallest": { "t": "el más pequeño", "p": "[ˈsmɔːlɪst]" },
  "function": { "t": "función, funcionar", "p": "[ˈfʌŋkʃn]" },
  "functions": { "t": "funciones", "p": "[ˈfʌŋkʃnz]" },
  "functional": { "t": "funcional", "p": "[ˈfʌŋkʃənl]" }
};

if (typeof module !== 'undefined') {
  module.exports = OFFLINE_DICTIONARY;
}
if (typeof self !== 'undefined') {
  self.OFFLINE_DICTIONARY = OFFLINE_DICTIONARY;
}
if (typeof window !== 'undefined') {
  window.OFFLINE_DICTIONARY = OFFLINE_DICTIONARY;
}
